### ISSUE TITLE
Telegram.php faylini qayerdan olamiz?

### ISSUE THREAD

**Issue by sjomurodov** [shoxruxrashidov/Telegram-PHP-API#3]
Readme da yozilgan Telegram.php qaysi papkada joylashgan, izlab topolmadim?

**Comment by mrrashidov** [comment]
> Readme da yozilgan Telegram.php qaysi papkada joylashgan, izlab topolmadim?

Assalomu alaykum savol uchun raxmat xozir ushbu kutubhonani takomillashtirish ustida ishlayotganim uchun kora olmadingiz va namunadagi fayllar kerak bolsa commentlar otmishidan korishingiz mumkin edi 
 [namuna](https://github.com/mrrashidov/Telegram-PHP-API/tree/91b89cb2c13e2f20d2f3853bc549cb23a1838d06)
